// Vercel build script — generates js/config.js from environment variables.
// Run automatically by Vercel before serving the static site.
const fs = require('fs');

const url = process.env.SUPABASE_URL || '';
const key = process.env.SUPABASE_KEY || '';
const ai  = process.env.AI_API_KEY   || '';

if (!url || !key) {
  console.error('[build] ERROR: SUPABASE_URL and SUPABASE_KEY must be set in Vercel environment variables.');
  process.exit(1);
}

const content = `// Auto-generated by build.js — do not edit manually.
const SUPABASE_URL = "${url}";
const SUPABASE_KEY = "${key}";
const AI_API_KEY   = "${ai}";
`;

fs.writeFileSync('js/config.js', content, 'utf8');
console.log('[build] js/config.js generated successfully.');
